# Generated by Django 3.0.14 on 2021-06-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='discount_price',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
