# Generated by Django 3.2.2 on 2021-07-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
