# Generated by Django 3.0.14 on 2021-05-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='label',
            field=models.CharField(choices=[('Y', 'Available'), ('N', 'Out of Stock')], default='Y', max_length=1),
        ),
    ]
