# Generated by Django 3.2.2 on 2021-07-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_items_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
