# Generated by Django 3.2.2 on 2021-07-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_refund'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
