# Generated by Django 3.2.2 on 2021-06-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_items_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='size',
            field=models.CharField(choices=[('K', '108 x 120'), ('Q', '90 x 108')], default='K', max_length=1),
        ),
    ]
