# Generated by Django 3.2.2 on 2021-06-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210623_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='featured',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
