# Generated by Django 3.0.14 on 2021-05-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210526_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='pincode',
            field=models.IntegerField(default='700000'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_type',
            field=models.CharField(choices=[('S', 'Shipping'), ('B', 'Billing')], max_length=1),
        ),
    ]
