# Generated by Django 3.2 on 2021-06-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210526_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_type',
            field=models.CharField(choices=[('S', 'Shipping'), ('B', 'Billing')], max_length=1),
        ),
    ]
