# Generated by Django 3.2.2 on 2021-06-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_items_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='availablity',
            new_name='availability',
        ),
    ]
