# Generated by Django 3.2.2 on 2021-06-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_availablity_items_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
