# Generated by Django 3.2.2 on 2021-06-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_items_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='size',
            field=models.CharField(choices=[('King', 'King - 108 x 120'), ('Queen', 'Queen - 90 x 108'), ('Single', 'Single'), ('Double', 'Double')], default='King', max_length=10),
        ),
    ]
