# Generated by Django 3.2.2 on 2021-06-24 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_items_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
