# Generated by Django 3.2.2 on 2021-06-24 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_items_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
